/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:67ea35b7-db53-4e7f-8a0c-a136730a5e19",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Il0KDQZys",
    "aws_user_pools_web_client_id": "34go2mr267kmcnr38log8cbllb",
    "oauth": {
        "domain": "googlesignin-staging.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://main.dpdzznty4hgmh.amplifyapp.com/,http://localhost:3000/",
        "redirectSignOut": "https://main.dpdzznty4hgmh.amplifyapp.com/,http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
